project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    comments:
      hypothesis: true
    citations-hover: true
    crossrefs-hover: true
    toc: true
    toc-location: left
    title-block-style: manuscript
  elsevier-pdf:
    keep-tex: true
  docx: default



